#ifndef HUFFMAN_TREE_HPP
#define HUFFMAN_TREE_HPP

#include <unordered_map>
#include <string>
#include <fstream>
#include "HuffmanNode.hpp"

using namespace std;

// HuffmanTree builds and owns the Huffman binary tree, generates the binary
// code for every character, and knows how to save/load the tree's shape
// to/from a file (so the decompressor can rebuild the exact same tree).
class HuffmanTree
{
private:
    HuffmanNode *root;

    // Maps each character to its generated binary Huffman code, e.g. 'a' -> "010"
    unordered_map<unsigned char, string> huffmanCodes;

    // Recursively walks the tree, building up "code" as it goes left (append '0')
    // or right (append '1'). When a leaf is reached, the accumulated code is
    // stored as that character's Huffman code.
    void generateCodes(HuffmanNode *node, const string &code);

    // Recursively writes the tree's shape to the output file so it can be
    // rebuilt later. Uses a simple preorder traversal:
    //   '0' = internal node (recurse into left, then right)
    //   '1' = leaf node, followed by the character byte itself
    //   'X' = missing child (only used for the 1-unique-character edge case)
    void writeTreeToFile(HuffmanNode *node, ofstream &outFile);

    // The exact reverse of writeTreeToFile(): reads the markers back and
    // reconstructs the same tree shape.
    HuffmanNode *readTreeFromFile(ifstream &inFile);

public:
    HuffmanTree();
    ~HuffmanTree();

    // Builds the Huffman tree from a map of character -> frequency using a
    // min-heap (priority_queue), then immediately generates the codes.
    void buildTree(const unordered_map<unsigned char, int> &frequencies);

    // Returns the character -> code map generated by buildTree().
    unordered_map<unsigned char, string> getCodes() const;

    HuffmanNode *getRoot() const;

    // Save/restore the tree's shape to/from a compressed file.
    void serializeTree(ofstream &outFile);
    void deserializeTree(ifstream &inFile);
};

#endif
